//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userinterface.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("userinterface.Properties.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string DeviceAddDevice {
            get {
                return ResourceManager.GetString("DeviceAddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device Group.
        /// </summary>
        public static string DeviceAddDeviceGroup {
            get {
                return ResourceManager.GetString("DeviceAddDeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Groups.
        /// </summary>
        public static string DeviceDeviceGroups {
            get {
                return ResourceManager.GetString("DeviceDeviceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DeviceDevices {
            get {
                return ResourceManager.GetString("DeviceDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string MainWindowApplySettingsButton {
            get {
                return ResourceManager.GetString("MainWindowApplySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string MainWindowDevicesButton {
            get {
                return ResourceManager.GetString("MainWindowDevicesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string MainWindowMappingsButton {
            get {
                return ResourceManager.GetString("MainWindowMappingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string MainWindowNavigationTitle {
            get {
                return ResourceManager.GetString("MainWindowNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string MainWindowProfilesButton {
            get {
                return ResourceManager.GetString("MainWindowProfilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry.
        /// </summary>
        public static string MappingAddEntry {
            get {
                return ResourceManager.GetString("MappingAddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mapping.
        /// </summary>
        public static string MappingAddMapping {
            get {
                return ResourceManager.GetString("MappingAddMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Profile.
        /// </summary>
        public static string ProfileAddNewProfile {
            get {
                return ResourceManager.GetString("ProfileAddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode is for experts only..
        /// </summary>
        public static string ProfileExpertsOnlyWarning {
            get {
                return ResourceManager.GetString("ProfileExpertsOnlyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to Data.
        /// </summary>
        public static string ProfileFitToData {
            get {
                return ResourceManager.GetString("ProfileFitToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: x1,y1,x2,y2,...xn,yn;.
        /// </summary>
        public static string ProfileLUTFormatInstructions {
            get {
                return ResourceManager.GetString("ProfileLUTFormatInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Zoom.
        /// </summary>
        public static string ProfileResetZoom {
            get {
                return ResourceManager.GetString("ProfileResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string SettingsGeneralSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsGeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
